# Generated by Django 6.0.2 on 2026-02-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('cca3', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('cca2', models.CharField(db_index=True, max_length=2)),
                ('common_name', models.CharField(max_length=255)),
                ('official_name', models.CharField(max_length=255)),
                ('capital', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(db_index=True, max_length=100)),
                ('subregion', models.CharField(blank=True, max_length=100, null=True)),
                ('population', models.BigIntegerField(db_index=True)),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('flag_url', models.URLField(blank=True, max_length=500, null=True)),
                ('currencies', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['common_name'],
            },
        ),
    ]
